name: Test
on:
  workflow_dispatch: # manually
  schedule: # nightly
    - cron: "0 0 * * *"
  pull_request: {}
  merge_group:
    branches:
      - main
  push: # on push to the main branch
    branches:
      - main
env:
  DD_APPSEC_WAF_TIMEOUT: 5s
jobs:
  native:
    name: Native ${{ matrix.runs-on }} (Go ${{ matrix.go-version }}, CGO_ENABLED=${{ matrix.cgo_enabled }})
    strategy:
      matrix:
        runs-on: [ macos-14, macos-13, macos-12, ubuntu-22.04, ubuntu-20.04, windows-latest ]
        go-version: [ "1.22", "1.21" ]
        cgo_enabled: [ "0", "1" ] # test it compiles with and without cgo
      fail-fast: false
    runs-on: ${{ matrix.runs-on }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}
          cache: true

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-pkg-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: go-pkg-mod-

      - name: go test
        shell: bash
        run: |
          # Install gotestsum
          env GOBIN=$PWD go install gotest.tools/gotestsum@latest
          # Run the tests with gotestsum
          env CGO_ENABLED=${{ matrix.cgo_enabled }} ./gotestsum -- -v ./... || true

  # Same tests but on the official golang container for linux
  golang-linux-container:
    name: Docker golang:${{ matrix.go-version }}-${{ matrix.distribution }} (CGO_ENABLED=${{ matrix.cgo_enabled }})
    runs-on: ubuntu-latest
    container:
      image: golang:${{ matrix.go-version }}-${{ matrix.distribution }}
    strategy:
      matrix:
        go-version: [ "1.22", "1.21" ]
        distribution: [ bookworm, bullseye, alpine ]
        cgo_enabled: [ "0", "1" ] # test it compiles with and without cgo
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      # Install gcc and the libc headers on alpine images
      - if: ${{ matrix.distribution == 'alpine' }}
        run: apk add gcc musl-dev libc6-compat git

      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-pkg-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: go-pkg-mod-

      - name: go test
        run: |
          # Install gotestsum
          env GOBIN=$PWD go install gotest.tools/gotestsum@latest
          # Run the tests with gotestsum
          env CGO_ENABLED=${{ matrix.cgo_enabled }} ./gotestsum -- -v ./... || true

  linux-arm64:
    name: Linux ARM64 (CGO_ENABLED=${{ matrix.cgo_enabled }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        cgo_enabled: [ "0", "1" ] # test it compiles with and without the cgo
      fail-fast: false
    steps:
      - uses: actions/checkout@v3
      - name: Go modules cache
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: go-pkg-mod-${{ hashFiles('**/go.sum') }}
          restore-keys: go-pkg-mod-
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
        with:
          platforms: arm64
      - run: docker run --platform=linux/arm64 -v $PWD:$PWD -w $PWD -eCGO_ENABLED=${{ matrix.cgo_enabled }} -eDD_APPSEC_WAF_TIMEOUT=$DD_APPSEC_WAF_TIMEOUT golang go test -v ./...

  everything:
    name: All Tests
    needs:
      - native
      - golang-linux-container
      - linux-arm64
    runs-on: ubuntu-latest
    steps:
      - name: Completed
        run: echo "All tests completed!"
